p8105_hw1_ei2262
================

# Problem 1

## Description of `penguins` Dataset

    ## # A tibble: 344 × 8
    ##    species island    bill_length_mm bill_depth_mm flipper_…¹ body_…² sex    year
    ##    <fct>   <fct>              <dbl>         <dbl>      <int>   <int> <fct> <int>
    ##  1 Adelie  Torgersen           39.1          18.7        181    3750 male   2007
    ##  2 Adelie  Torgersen           39.5          17.4        186    3800 fema…  2007
    ##  3 Adelie  Torgersen           40.3          18          195    3250 fema…  2007
    ##  4 Adelie  Torgersen           NA            NA           NA      NA <NA>   2007
    ##  5 Adelie  Torgersen           36.7          19.3        193    3450 fema…  2007
    ##  6 Adelie  Torgersen           39.3          20.6        190    3650 male   2007
    ##  7 Adelie  Torgersen           38.9          17.8        181    3625 fema…  2007
    ##  8 Adelie  Torgersen           39.2          19.6        195    4675 male   2007
    ##  9 Adelie  Torgersen           34.1          18.1        193    3475 <NA>   2007
    ## 10 Adelie  Torgersen           42            20.2        190    4250 <NA>   2007
    ## # … with 334 more rows, and abbreviated variable names ¹​flipper_length_mm,
    ## #   ²​body_mass_g

The dataset `penguins` focuses on the following descriptive
characteristics of penguins:

1.  Type of species
2.  Island of origin
3.  Bill length of penguin(in mm)
4.  Bill depth of penguin(in mm)
5.  Flipper length of penguin(in mm)
6.  Body mass of penguin(in g)
7.  Sex of penguin
8.  Year penguin was born

<!-- -->

    ## [1] 344

    ## [1] 8

    ## [1] 200.9152

The dataset contains 344 rows and 8 columns. The mean flipper length is
200.92 mm.

## Scatterplot

The following is a scatterplot with `bill_length_mm` on the x-axis and
`flipper_length_mm`on the y-axis. The dataset is color coordinated based
on the variable `species`.

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_ei2262_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

The scatterplot was exported as a pdf to my project directory using
`ggsave`. It was named “penguinsplot.”

# Problem 2

``` r
hw_df = tibble(
  vec_numeric = rnorm(n = 10),
  vec_logical = vec_numeric > 0,
  vec_character = c("d","s","h","o","m","e","w","o","r","k"),
  vec_factor = factor(c("high", "med","high","high","high","low","low","low","med","med"))
)

mean(pull(hw_df, vec_numeric))
```

    ## [1] -0.4263979

``` r
mean(pull(hw_df, vec_logical))
```

    ## [1] 0.2

``` r
mean(pull(hw_df, vec_character))
```

    ## Warning in mean.default(pull(hw_df, vec_character)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(hw_df, vec_factor))
```

    ## Warning in mean.default(pull(hw_df, vec_factor)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

After creating the dataframe, I tried calculating the mean of each
variable. The variables that produced an output were *vec_numeric* and
*vec_logical*. The variables that did not produce an output wer
*vec_character* and *vec_factor*.

# Applying `as.numeric`

``` r
hw_df = tibble(
  vec_numeric = rnorm(n = 10),
  vec_logical = as.numeric(vec_numeric > 0),
  vec_character = as.numeric(c("d","s","h","o","m","e","w","o","r","k")),
  vec_factor = as.numeric(factor(c("high", "med","high","high","high","low","low","low","med","med")))
)
```
